Resources:
  EC2Instance1:
    Type: AWS::EC2::Instance
    Properties:
  
      ImageId: ami-0c94855ba95c71c99  
      InstanceType: t2.micro
  EC2Instance2:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0c94855ba95c71c99
      InstanceType: t2.micro
  EC2Instance3:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0c94855ba95c71c99
      InstanceType: t2.micro
  EC2Instance4:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0c94855ba95c71c99
      InstanceType: t2.micro
  EC2Instance5:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0c94855ba95c71c99
      InstanceType: t2.micro

  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: my-s3-bucket  